openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/auth/register:
    post:
      summary: ''
      operationId: postApiAuthRegister
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'Auth Managent'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: ab
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: morton62@example.net
                password:
                  type: string
                  description: 'Must be at least 8 characters.'
                  example: PZYQ7mM
                password_confirm:
                  type: string
                  description: 'The value and <code>password</code> must match.'
                  example: et
              required:
                - name
                - email
                - password
                - password_confirm
      security: []
  /api/auth/signin:
    post:
      summary: ''
      operationId: postApiAuthSignin
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'Auth Managent'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: schaden.athena@example.com
                password:
                  type: string
                  description: ''
                  example: nam
              required:
                - email
                - password
      security: []
  /api/candy:
    get:
      summary: 'Display a listing of candies.'
      operationId: displayAListingOfCandies
      description: 'Get a list of candies.'
      parameters:
        -
          in: query
          name: per_page
          description: 'Size per page. Defaults to 15.'
          example: 18
          required: false
          schema:
            type: integer
            description: 'Size per page. Defaults to 15.'
            example: 18
        -
          in: query
          name: page
          description: 'Page to view.'
          example: 18
          required: false
          schema:
            type: integer
            description: 'Page to view.'
            example: 18
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data: []
                  links:
                    first: 'http://localhost/api/candy?page=1'
                    last: 'http://localhost/api/candy?page=1'
                    prev: 'http://localhost/api/candy?page=17'
                    next: null
                  meta:
                    current_page: 18
                    from: null
                    last_page: 1
                    links:
                      -
                        url: 'http://localhost/api/candy?page=17'
                        label: '&laquo; Previous'
                        active: false
                      -
                        url: 'http://localhost/api/candy?page=1'
                        label: '1'
                        active: false
                      -
                        url: null
                        label: 'Next &raquo;'
                        active: false
                    path: 'http://localhost/api/candy'
                    per_page: 18
                    to: null
                    total: 2
                properties:
                  data:
                    type: array
                    example: []
                  links:
                    type: object
                    properties:
                      first:
                        type: string
                        example: 'http://localhost/api/candy?page=1'
                      last:
                        type: string
                        example: 'http://localhost/api/candy?page=1'
                      prev:
                        type: string
                        example: 'http://localhost/api/candy?page=17'
                      next:
                        type: string
                        example: null
                  meta:
                    type: object
                    properties:
                      current_page:
                        type: integer
                        example: 18
                      from:
                        type: string
                        example: null
                      last_page:
                        type: integer
                        example: 1
                      links:
                        type: array
                        example:
                          -
                            url: 'http://localhost/api/candy?page=17'
                            label: '&laquo; Previous'
                            active: false
                          -
                            url: 'http://localhost/api/candy?page=1'
                            label: '1'
                            active: false
                          -
                            url: null
                            label: 'Next &raquo;'
                            active: false
                        items:
                          type: object
                          properties:
                            url:
                              type: string
                              example: 'http://localhost/api/candy?page=17'
                            label:
                              type: string
                              example: '&laquo; Previous'
                            active:
                              type: boolean
                              example: false
                      path:
                        type: string
                        example: 'http://localhost/api/candy'
                      per_page:
                        type: integer
                        example: 18
                      to:
                        type: string
                        example: null
                      total:
                        type: integer
                        example: 2
      tags:
        - 'Candy Managent'
      security: []
    post:
      summary: 'Store a newly created resource in storage.'
      operationId: storeANewlyCreatedResourceInStorage
      description: 'Só um teste qualquer'
      parameters: []
      responses: {  }
      tags:
        - 'Candy Managent'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                candy_name:
                  type: string
                  description: ''
                  example: enim
                amount:
                  type: integer
                  description: ''
                  example: 6
              required:
                - candy_name
                - amount
      security: []
  '/api/candy/{id}':
    get:
      summary: 'Display the specified Candy.'
      operationId: displayTheSpecifiedCandy
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 1
                    candy: 'Red Velvet'
                    amount: 50
                    created_at: '2023-04-26T13:03:39.000000Z'
                    updated_at: '2023-04-26T13:03:39.000000Z'
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      candy:
                        type: string
                        example: 'Red Velvet'
                      amount:
                        type: integer
                        example: 50
                      created_at:
                        type: string
                        example: '2023-04-26T13:03:39.000000Z'
                      updated_at:
                        type: string
                        example: '2023-04-26T13:03:39.000000Z'
      tags:
        - 'Candy Managent'
      security: []
    put:
      summary: 'Update the specified resource in storage.'
      operationId: updateTheSpecifiedResourceInStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'Candy Managent'
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                candy_name:
                  type: string
                  description: ''
                  example: voluptates
                amount:
                  type: integer
                  description: ''
                  example: 2
      security: []
    delete:
      summary: 'Remove the specified resource from storage.'
      operationId: removeTheSpecifiedResourceFromStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'Candy Managent'
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'Candy ID'
        example: 3
        required: true
        schema:
          type: integer
  /api/login:
    post:
      summary: 'Attempt to authenticate a new session.'
      operationId: attemptToAuthenticateANewSession
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: ''
                  example: lori.morar@example.com
                password:
                  type: string
                  description: ''
                  example: 'sUY2!&<'
              required:
                - email
                - password
      security: []
  /api/logout:
    post:
      summary: 'Destroy an authenticated session.'
      operationId: destroyAnAuthenticatedSession
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/forgot-password:
    post:
      summary: 'Send a reset link to the given user.'
      operationId: sendAResetLinkToTheGivenUser
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/reset-password:
    post:
      summary: "Reset the user's password."
      operationId: resetTheUsersPassword
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  description: ''
                  example: eius
                password:
                  type: string
                  description: ''
                  example: porro
              required:
                - token
                - password
      security: []
  /api/register:
    post:
      summary: 'Create a new registered user.'
      operationId: createANewRegisteredUser
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/user/profile-information:
    put:
      summary: "Update the user's profile information."
      operationId: updateTheUsersProfileInformation
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/user/password:
    put:
      summary: "Update the user's password."
      operationId: updateTheUsersPassword
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/user/confirmed-password-status:
    get:
      summary: 'Get the password confirmation status.'
      operationId: getThePasswordConfirmationStatus
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/user/confirm-password:
    post:
      summary: "Confirm the user's password."
      operationId: confirmTheUsersPassword
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
tags:
  -
    name: 'Auth Managent'
    description: "\nAPIs to manage the Auth resource"
  -
    name: 'Candy Managent'
    description: "\nAPIs to manage the cnady resource"
  -
    name: Endpoints
    description: ''
